version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: database
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - '4306:3306'
    volumes:
      - ./docker/database/data:/var/lib/mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

  app:
    build:
      context: .
      dockerfile: ./docker/nest/Dockerfile
    container_name: nest-docker
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - database
    volumes:
      - ./backend/src:/app/src

  frontend:
    build:
      context: .
      dockerfile: ./docker/angular/Dockerfile
    container_name: frontend
    environment:
      - PORT=${PORT}
    ports:
      - '4200:4200'
    depends_on:
      - nest-docker
    volumes:
      - ./frontend/src:/www/src

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
